name: deploy

on:
    push:
        branches:
            - main

jobs:
  test:
    runs-on: ubuntu-22.04  # note: software run environment
    steps:  # note: ubuntu on pipeline
      - name: Checkout repository
        uses: actions/checkout@v3  # actions market 
      - name: Node.js setup
        uses: actions/setup-node@v3  # actions market
        with:
          node-version: "18"
      - name: install npm packages
        run: npm ci
      - name: install and run redis-server
        run: |
          sudo apt-get update
          sudo apt-get install -y redis-server
          redis-server  --daemonize yes --requirepass test_env --port 6380
      - name: Run test
        run: npm run test:ci

      - name: test build
        run: npm run build
  deploy:  # note: variable
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up SSH
          run: |
                mkdir -p ~/.ssh/
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa

            - name: Set up known hosts
              run: |
                echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
                chmod 644 ~/.ssh/known_hosts
            
            - name: SSH and deploy
              run: |
                ssh ${{ secrets.SSH_USERNAME}}@${{ secrets.SSH_PUBLIC_IP}} "
                    cd express
                    git pull
                    npm install || exit 1
                    npm run build || exit 1
                    sudo pkill node || exit 1
                    sudo npm run start & npx wait-on http://localhost
                    exit
                "
