name: test

on: pull_request  # note: trigger

jobs:
  test:
    runs-on: ubuntu-22.04  # note: software run environment
    steps:  # note: ubuntu on pipeline
      - name: Checkout repository
        uses: actions/checkout@v3  # actions market 
      - name: Node.js setup
        uses: actions/setup-node@v3  # actions market
        with:
          node-version: "18"
      - name: install npm packages
          run: npm ci
      - name: install and run redis-server
          run: |
          sudo apt-get update
          sudo apt-get install -y redis-server
          redis-server  --daemonize yes --requirepass test_env --port 6380
      - name: Run test
          run: npm run test:ci

      - name: test build
          run: npm run build
